sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7.0
  - 2.6.3
gemfile:
  - gemfiles/activerecord-52.gemfile
before_install:
  - gem i bundler
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services:
  - mysql
env:
  - DB=sqlite
  - DB=mysql MYSQL_RESTART_COMMAND="sudo service mysql restart"
  - NO_TIMESTAMP=false
  - NO_TIMESTAMP=true
